                                &MOLECULE
                                    NMOL              1
                                    CONN_FILE_NAME    ../topologies/Carbon.psf
                                    CONN_FILE_FORMAT  UPSF
                               &END MOLECULE
                                &MOLECULE
                                    NMOL              2
                                    CONN_FILE_NAME    ../topologies/Hydrogen.psf
                                    CONN_FILE_FORMAT  UPSF
                               &END MOLECULE
                                &MOLECULE
                                    NMOL              1
                                    CONN_FILE_NAME    ../topologies/Carbon.psf
                                    CONN_FILE_FORMAT  UPSF
                               &END MOLECULE
                                &MOLECULE
                                    NMOL              2
                                    CONN_FILE_NAME    ../topologies/Hydrogen.psf
                                    CONN_FILE_FORMAT  UPSF
                               &END MOLECULE
